### ISSUE TITLE
Set up the copilot agent environment

### ISSUE THREAD

**Issue by mattleibow** [mattleibow/DeviceRunners#42]
This docs describes what to do: https://docs.github.com/en/copilot/customizing-copilot/customizing-the-development-environment-for-copilot-coding-agent

This is an example I am using on another repo:

```yml
name: "Copilot Setup Steps"

on: workflow_dispatch

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Run a pre-work build
        shell: pwsh
        run: .\build.ps1
```
